### model
model_name_or_path:  path-to-/sft_qwen/decop_1
quantization_bit: 4

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: train_decop_1
template: qwen
cutoff_len: 2048
max_samples: 679
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen_sft_dpo/train_decop_1
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
